Rpc generator fix to generate optional floats
smartdevicelink/sdl_ios pull request #1777
Opened 2020-09-10 14:30 UTC by FrankElias77

Fixes #1763

### Risk
This PR makes **[no / minor / major]** API changes.

### Testing Plan
- [x] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [ ] I have run the unit tests with this PR
- [ ] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).

#### Unit Tests
N/A

#### Core Tests
N/A

Core version / branch / commit hash / module tested against: N/A
HMI name / version / branch / commit hash / module tested against: N/A

### Summary
Fixed the generator init function that was not properly generating float optional values.

### Changelog
##### Breaking Changes
* N/A

##### Enhancements
* N/A

##### Bug Fixes
* Fixed the generator init function that was not properly generating float optional values.

### Tasks Remaining:
N/A

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

2020-09-16 19:04 UTC, NicoleYarroch commented on generator/transformers/common_producer.py
> +        elif not param.is_mandatory and re.match(r'\w*float\d*', data['type_native']):
Can this `elif` be combined into one statement with the above `if` like so: `re.match(r'\w*Int\d*|BOOL|\w*float\d*', data['type_native'])`?

2020-09-16 19:13 UTC, NicoleYarroch requested changes
Left some comments

2020-09-16 19:13 UTC, NicoleYarroch commented on generator/transformers/common_producer.py
> +        if mandatory or re.match(r'BOOL|double', type_native):
I think we can also get rid of the `double` since it appears we only have `SDLFloat` in **NSNumber+NumberType.h**.

2020-09-16 19:13 UTC, NicoleYarroch commented on generator/transformers/common_producer.py
> +        elif not param.is_mandatory and re.match(r'\w*float\d*', data['type_native']):
Can this `elif` be combined into one statement with the above `if` like so: `re.match(r'\w*Int\d*|BOOL|\w*float\d*', data['type_native'])`?

2020-09-18 15:00 UTC, joeljfischer commented on generator/transformers/common_producer.py
> +        if not param.is_mandatory and re.match(r'\w*Int\d*|BOOL|\w*float\d*', data['type_native']):
Is that what we do for ints as well? I thought we took regular floats / ints instead of it's required.

2020-09-18 15:13 UTC, NicoleYarroch commented on generator/transformers/common_producer.py
> +        if not param.is_mandatory and re.match(r'\w*Int\d*|BOOL|\w*float\d*', data['type_native']):
Oh, I get it now, we use `NSNumber` for optionals because primitives can't be set to `null`. Ignore my previous comment.

2020-09-18 15:14 UTC, NicoleYarroch approved these changes

2020-09-18 17:33 UTC, merged