Resolves typos in `sdl_ios/docs/Classes/`
smartdevicelink/sdl_ios pull request #1788
Opened 2020-09-22 13:19 UTC by jordynmackool

Fixes issue #1787 

### Risk
This PR makes **[no]** API changes.

### Summary
Resolves typos as listed in issue #1787 

### CLA
- [X] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

2020-09-22 17:35 UTC, theresalech approved these changes
This looks good to me! @joeljfischer, can you please merge at your convenience?

2020-09-23 20:30 UTC, theresalech requested changes
@jordynmackool, I've suggested a few changes. Please let me know if you have any questions!

2020-09-23 20:30 UTC, theresalech commented on docs/Classes/SDLAddCommand.html
> +<p>@discussion If provided, defines the image to be shown along with a command. If omitted on supported displays, no (or the default if applicable) icon will be displayed</p>
```suggestion
<p>@discussion If provided, defines the image to be shown along with a command. If omitted on supported displays, no (or the default if applicable) icon will be displayed.</p>
```

2020-09-23 20:30 UTC, theresalech commented on docs/Classes/SDLDisplayCapability.html
> +  <p>Init with all the prosperities</p>
```suggestion
  <p>Init with all the properties</p>
```

2020-09-23 20:30 UTC, theresalech commented on docs/Classes/SDLPerformInteraction.html
> +  <p>Convenience init for setting the single visual or voice-recognition menu choice.</p>
```suggestion
  <p>Convenience init for setting a single visual or voice-recognition menu choice.</p>
```

2020-09-23 20:30 UTC, theresalech commented on docs/Classes/SDLScreenManager.html
> +<p>If set to <code>SDLDynamicMenuUpdatesModeForceOff</code>, menu updates will work the legacy way. This means when a new menu is set the entire old menu is deleted and add commands are created for e
```suggestion
<p>If set to <code>SDLDynamicMenuUpdatesModeForceOff</code>, menu updates will work the legacy way. This means when a new menu is set, the entire old menu is deleted and add commands are created for every item regardless of if the item appears in both the old and new menu. This method is RPCs heavy and may cause some failures when creating and updating large menus.</p>
```

2020-09-23 20:30 UTC, theresalech commented on docs/Classes/SDLSeatControlCapabilities.html
> +      <dd><p>Whether or not horizontal Position is available</p></dd>
```suggestion
      <dd><p>Whether or not horizontal position is available</p></dd>
```

2020-09-23 20:30 UTC, theresalech commented on docs/Classes/SDLStreamingMediaConfiguration.html
> +    <p>Apps using views outside of the <code>UIView</code> hierarchy (such as OpenGL) are currently unsupported. If you app uses partial views in the hierarchy, only those views will be discovered. Y
```suggestion
    <p>Apps using views outside of the <code>UIView</code> hierarchy (such as OpenGL) are currently unsupported. If your app uses partial views in the hierarchy, only those views will be discovered. Your OpenGL views will not be discoverable to a haptic interface head unit and you will have to manually make these views discoverable via the <code><a href="../Classes/SDLSendHapticData.html">SDLSendHapticData</a></code> RPC request.</p>
```

2020-09-23 20:30 UTC, theresalech commented on docs/Classes/SDLStreamingMediaConfiguration.html
> +      <dd><p>The UIViewController with the content that is being streamed on, to use for haptics if needed and possible (only works for UIViews)</p></dd>
```suggestion
      <dd><p>The UIViewController with the content that is being streamed on, to use for haptics if needed and possible (only works for UIViews).</p></dd>
```

2020-09-23 20:30 UTC, theresalech commented on docs/Classes/SDLStreamingMediaConfiguration.html
> +      <dd><p>The UIViewController with the content that is being streamed on, to use for haptics if needed and possible (only works for UIViews)</p></dd>
```suggestion
      <dd><p>The UIViewController with the content that is being streamed on, to use for haptics if needed and possible (only works for UIViews).</p></dd>
```

2020-09-23 20:30 UTC, theresalech commented on docs/Classes/SDLTextField.html
> +  <p>Convenience initializer for the TextField RPC struct</p>
```suggestion
  <p>Convenience initializer for the TextField RPC struct.</p>
```

2020-09-23 20:30 UTC, theresalech commented on docs/Enums/SDLSystemCapabilityManagerError.html
> +  <p>You must be in an HMI Level other than NONE to request or subscribe to capabilities other than DISPLAYS</p>
```suggestion
  <p>You must be in an HMI level other than NONE to request or subscribe to capabilities other than DISPLAYS.</p>
```

2020-09-24 17:38 UTC, jordynmackool commented
@theresalech, thanks for the review. I have made committed your suggested changes.

2020-09-24 21:01 UTC, theresalech approved these changes
Looks good to me! @joeljfischer, please merge when you get the chance!

2020-09-25 13:17 UTC, merged