Swift Package Manager support
smartdevicelink/sdl_ios pull request #1812
Opened 2020-10-14 18:33 UTC by joeljfischer

Fixes #1387 

### Risk
This PR makes **no** API changes.

### Testing Plan
- [x] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [x] I have run the unit tests with this PR
- [x] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).

#### Unit Tests
No unit tests changed, but some merge conflicts were fixed

#### Core Tests
A SPM test app was run with basic text update and lock screen tests.

Core version / branch / commit hash / module tested against: Manticore (Core v6.1.1)
HMI name / version / branch / commit hash / module tested against: Manticore (generic_hmi v0.8.1)

### Summary
This PR adds support for Swift Package Manager. Note that the bson_c_lib dependency will need to be updated when [this PR](https://github.com/smartdevicelink/bson_c_lib/pull/49) is merged and release 1.2.2 occurs.

### Changelog
##### Enhancements
* Adds support for using SDL iOS as a Swift Package through Xcode 12+.

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

2020-10-15 18:43 UTC, NicoleYarroch requested changes
I left one question.

2020-10-15 19:35 UTC, joeljfischer commented on SmartDeviceLink-iOS.xcodeproj/project.pbxproj
> +		4A877499251BBE2400A8BEBB /* (null) in Headers */ = {isa = PBXBuildFile; settings = {ATTRIBUTES = (Public, ); }; };
Done

2020-10-16 12:25 UTC, NicoleYarroch requested changes
SPM should be added to the list of supported dependency managers in the **README** file. If there is a SPM badge it should also be added.

2020-10-16 13:35 UTC, joeljfischer commented
Fixed

2020-10-16 14:27 UTC, NicoleYarroch requested changes
One change requested.

2020-10-16 14:27 UTC, NicoleYarroch commented on README.md
> +[![Accio compatible](https://img.shields.io/badge/Accio-compatible-4BC51D.svg?style=flat)](https://github.com/JamitLabs/Accio)
This paragraph also needs to get updated:

> There are instructions on how to install using the dependency managers CocoaPods, Carthage, and Accio, as well as how to install the library framework manually.

2020-10-16 15:01 UTC, NicoleYarroch approved these changes

2020-10-16 15:38 UTC, merged