Bugfix/battery drain issue
smartdevicelink/sdl_ios pull request #1815
Opened 2020-10-16 12:04 UTC by kshala-ford

Fixes #1799 and #1809

### Risk
This PR makes **no** API changes.

### Testing Plan
- [ ] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [ ] I have run the unit tests with this PR
- [ ] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).

#### Unit Tests
TBD

Note: Unit tests to simulate the EA streams are planned. Feasibility must be confirmed because lot of mock classes might need to be created.

#### Core Tests
Only tested against various Ford SYNC3 systems.

### Summary
This PR is a mirror of a Ford internal fork. The goal is to improve stability within the SDL library regarding EA session and stream lifecycle. 

### Changelog
##### Bug Fixes
- Adds a force close for EA sessions upon EA disconnect notifications.
- Adds retry mechanism if IO thread could not be cancelled.
- Fixes a possible infinity loop that could cause a 100% load on the IO thread.
- Prevents a spam of EA connect notifications to execute further.
- Ends existing background task identifier upon EA disconnect notifications.

### Tasks Remaining:
- [ ] [Code review]
- [ ] [Write unit tests when applicable]
- [ ] [Test against other EA devices and make sure no regression is introduced]

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

2020-10-16 12:45 UTC, kshala-ford reviewed
I left some comments to the PR. Please let me know your thoughts.

2020-10-16 12:45 UTC, kshala-ford commented on SmartDeviceLink/private/SDLIAPDataSession.m
> +
As already mentioned for `destroySessionWithCompletionHandler` this method is not necessary. It's a copy and instead the destroy method should be called.
```suggestion
```

2020-10-16 12:45 UTC, kshala-ford commented on SmartDeviceLink/private/SDLIAPDataSession.m
> +                if (SDL_SYSTEM_VERSION_GREATER_THAN_OR_EQUAL_TO(@"14")) {
We should consider to abort the loop for any iOS version.

2020-10-16 12:45 UTC, kshala-ford commented on SmartDeviceLink/private/SDLIAPTransport.m
> +    _eaAccessoryConnectedTime = timeNow;
I can't remember any rationale for this change. Ignoring a notification can be very dangerous leading to no app connecting. Can you give us a reason why this code is needed?

2020-10-16 12:45 UTC, kshala-ford commented on SmartDeviceLink/private/SDLLifecycleManager.m
> +
I have not looked into the code if ackground tasks are ended elsewhere. I have the impression the iOS bug might be caused by task expiration not being handled properly. So the idea to end them when not needed anymore is good. However ending them without being in sync with the disconnect process is dangerous as the thread might survive and run at a 100% whenever the app's process comes back to life.

2020-10-16 18:25 UTC, joeljfischer requested changes

2020-10-16 18:40 UTC, kshala-ford commented on SmartDeviceLink/private/SDLIAPDataSession.m
> +        [self performSelector:@selector(sdl_doNothing) onThread:self.ioStreamThread withObject:nil waitUntilDone:NO];
Running Xcode analysis doesn't show any issue with this attempt. Looks like it's pretty safe to call self in a block immediately dispatched asynchronously.

2020-10-16 18:48 UTC, kshala-ford commented on SmartDeviceLink/private/SDLIAPDataSession.m
> +                if (SDL_SYSTEM_VERSION_GREATER_THAN_OR_EQUAL_TO(@"14")) {
OK. I removed the version check

2021-05-17 19:22 UTC, joeljfischer commented
Fixed by #1910

2021-05-17 19:22 UTC, closed without merging