Fix lockscreen bugs when displayMode is always
smartdevicelink/sdl_ios pull request #1842
Opened 2020-11-06 16:27 UTC by FrankElias77

Fixes #1826 

### Risk
This PR makes **no** API changes.

### Testing Plan
- [ ] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [ ] I have run the unit tests with this PR
- [ ] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).

#### Unit Tests
N/A

#### Core Tests
N/A

Core version / branch / commit hash / module tested against: N/A
HMI name / version / branch / commit hash / module tested against: N/A

### Summary
[Summary of PR changes]

### Changelog
##### Breaking Changes
* N/A

##### Enhancements
* N/A

##### Bug Fixes
* [Bug Fix Info]

### Tasks Remaining:
N/A

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

2020-11-18 16:49 UTC, joeljfischer requested changes

2020-11-18 16:49 UTC, joeljfischer commented on SmartDeviceLink/private/SDLLockScreenManager.m
> +        }
I think this could just be another && addition

2020-12-16 19:19 UTC, NicoleYarroch requested changes
The bugs reported in the issue have been fixed. However, a new bug was introduced. The details for reproducing are below: 

1. LockScreenConfiguration.displayMode has been set to `always`.
2. The last received `OnDriverDistraction.lockScreenDismissalEnabled` from the module was `true`. The user swiped to dismiss the lockscreen.
3. The module sends a `OnDriverDistraction` notification with `state = ON` and `lockScreenDismissalEnabled` to `false`.

##### Expected Behavior
Lock screen is shown (without the `OnDriverDistraction.lockScreenDismissalWarning`) and the user can not swipe to dismiss the lock screen.

##### Observed Behavior
Locks screen is not shown.

2021-03-05 16:39 UTC, NicoleYarroch requested changes
It looks like bug #3 in the issue report is now broken after the latest changes were made.

2021-03-09 18:01 UTC, NicoleYarroch requested changes
Smoke testing went well but I made a request for more tests to be added so we don't accidentally break the code in the future.

2021-03-10 13:06 UTC, NicoleYarroch requested changes
Left some comments

2021-03-10 13:06 UTC, NicoleYarroch commented on SmartDeviceLink/private/SDLLockScreenManager.m
> +            self.lockScreenDismissedByUser = NO;
Can you also add tests to **SDLLockScreenManagerSpec** test this line?

2021-03-10 13:06 UTC, NicoleYarroch commented on SmartDeviceLink/private/SDLLockScreenManager.m
> +        [self sdl_updateLockscreenViewControllerWithDismissableState:self.lockScreenDismissable];
Can you also add tests to **SDLLockScreenManagerSpec** test this line?

2021-03-10 18:53 UTC, NicoleYarroch requested changes
Left some comments

2021-03-10 18:53 UTC, NicoleYarroch commented on SmartDeviceLinkTests/DevAPISpecs/SDLLockScreenManagerSpec.m
> +                expect(testManager.lockScreenDismissable).to(equal(NO));
```suggestion
                expect(testManager.lockScreenDismissable).to(beFalse());
```

2021-11-03 12:52 UTC, joeljfischer commented
These issues are fixed on develop

2021-11-03 12:52 UTC, closed without merging