Feature/issue 1080 sdl 0198 media skip indicators
smartdevicelink/sdl_ios pull request #1865
Opened 2020-12-04 20:52 UTC by FrankElias77

Fixes #1080 

### Risk
This PR makes **[no / minor / major]** API changes.

### Testing Plan
- [ ] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [ ] I have run the unit tests with this PR
- [ ] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).

#### Unit Tests
[Describe the unit tests and behaviors added in this PR]

#### Core Tests
N/A

Core version / branch / commit hash / module tested against: [INSERT]
HMI name / version / branch / commit hash / module tested against: [INSERT]

### Summary
[Summary of PR changes]

### Changelog
##### Breaking Changes
* [Breaking change info]

##### Enhancements
* [Enhancement info]

##### Bug Fixes
* [Bug Fix Info]

### Tasks Remaining:
N/A

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

2021-01-19 20:07 UTC, NicoleYarroch requested changes
Some minor changes requested

2021-01-21 16:52 UTC, FrankElias77 commented on SmartDeviceLink/private/SDLRPCParameterNames.h
> +extern SDLRPCParameterName const SDLRPCParameterNameSeekStreamingIndicator;
I added it, since it was present in the generated

2021-01-22 16:11 UTC, NicoleYarroch commented on SmartDeviceLink/public/SDLSeekStreamingIndicator.h
> +- (instancetype)initWithType:(SDLSeekIndicatorType)type seekTime:(nullable NSNumber<SDLUInt> *)seekTime;
Add another convenience init that sets the `type` to `TIME`. 
```
+ (instancetype)seekIndicatorWithSeekTime:(unsigned int)seekTime;
```

2021-01-22 16:22 UTC, NicoleYarroch requested changes
Made one request to add a convenience init.

2021-01-26 19:21 UTC, NicoleYarroch approved these changes

2021-01-27 20:41 UTC, NicoleYarroch commented
@FrankElias77 The merge conflicts need to be fixed before I can merge this PR.

2021-01-29 15:06 UTC, NicoleYarroch approved these changes

2021-01-29 15:06 UTC, merged