SDL 0236 Update mismatch in TireStatus structure
smartdevicelink/sdl_ios pull request #1867
Opened 2020-12-05 21:45 UTC by yoooriii

…l and update proper test

[Things to note: Pull Requests **must** fix an issue. Discussion about the feature / bug takes place in the issue, discussion of the implementation takes place in the PR. Please also see the [Contributing Guide](https://github.com/smartdevicelink/sdl_ios/blob/master/.github/CONTRIBUTING.md) for information on branch naming and the CLA, and the [SmartDeviceLink GitHub Best Practices](https://d83tozu1c8tt6.cloudfront.net/media/resources/SDL_GitHub_BestPractices.pdf) document for more information on how to enter a pull request. Please create the PR as a draft until it is ready for review. Once this PR is ready for review, please request one from @smartdevicelink/ios and mark the PR as ready for review. 

Also, remember that all new public file headers should be added as public in the `File Inspector / Target Membership` pane, placed in the `SmartDeviceLink/public` folder on the file system, and added to `SmartDeviceLink.h`. Private files should be placed in the `SmartDeviceLink/private` folder.

Delete the above section when you've read it.]

Fixes #[issue number]

### Risk
This PR makes **[no / minor / major]** API changes.

### Testing Plan
- [ ] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [ ] I have run the unit tests with this PR
- [ ] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).

#### Unit Tests
[Describe the unit tests and behaviors added in this PR]

#### Core Tests
[List of tests performed against Core and behaviors verified]

Core version / branch / commit hash / module tested against: [INSERT]
HMI name / version / branch / commit hash / module tested against: [INSERT]

### Summary
[Summary of PR changes]

### Changelog
##### Breaking Changes
* [Breaking change info]

##### Enhancements
* [Enhancement info]

##### Bug Fixes
* [Bug Fix Info]

### Tasks Remaining:
- [ ] [Task 1]
- [ ] [Task 2]

### CLA
- [ ] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

2020-12-08 09:55 UTC, yoooriii commented
Hello @atiwari9, @mrapitis. Could you please review the PR? Thank you.

2020-12-08 13:58 UTC, atiwari9 commented
@standa1-ford  - Please take note.

2020-12-14 14:51 UTC, perryneal11 commented
@yoooriii This PR makes changes to the mobile API, can the risk section be updated?

2020-12-14 15:22 UTC, perryneal11 commented
@yoooriii Could we update the issue fixed to #1297 ?

2020-12-17 22:39 UTC, yoooriii commented
> @yoooriii This PR makes changes to the mobile API, can the risk section be updated?

Description updated to: it makes MINOR change

2020-12-18 16:35 UTC, perryneal11 commented
The first line of the PR references "fixes #1867", shouldn't it say, "fixes #1297 "?

2020-12-21 09:26 UTC, yoooriii commented on SmartDeviceLink/public/SDLTireStatus.h
>   Required
Done.

2020-12-21 09:27 UTC, yoooriii commented
> The first line of the PR references "fixes #1867", shouldn't it say, "fixes #1297 "?

Fixed.

2020-12-21 17:10 UTC, perryneal11 commented
@yoooriii I was able to run the tests successfully. 

The proposal lists this as a major change. Additionally, the author has this listed as a breaking change. So It should be notated here. The tasks remaining box should be checked as well.

2020-12-23 21:22 UTC, yoooriii commented
Let it be a major as the proposal claims.

2020-12-24 10:15 UTC, a-prykho commented
@perryneal11 we`ve updated description , could you please re-review this PR and approve?

2021-01-04 13:41 UTC, joeljfischer commented
Hi @yoooriii thanks for catching that this is a breaking (major) version change. We will need to discuss internally whether to make the next version of Core / app libs a major version change (which was not approved by the committee) or to pull this proposal from the next version.

2021-01-06 15:06 UTC, perryneal11 commented
@theresalech This is approved by ford

2021-06-29 16:29 UTC, LitvinenkoIra commented
@theresalech This PR is ready for Livio review. Thank you!

2021-06-29 17:56 UTC, theresalech commented
@LitvinenkoIra can you please confirm that Ford has approved the latest changes? It looks like their last approval was in January, prior to the most recent commits. Thank you!

2021-06-30 09:17 UTC, LitvinenkoIra commented
@perryneal11 Could you please confirm your approval?

2021-06-30 13:46 UTC, rbrigh25 commented
@theresalech @LitvinenkoIra 
Approved by Ford

2021-07-27 17:11 UTC, joeljfischer requested changes

2021-07-28 15:45 UTC, YuriiLokhmatovGitHub commented on SmartDeviceLinkTests/RPCSpecs/StructSpecs/SDLTireStatusSpec.m
> +// make all tires different to prevent misplacement (eg left front != right front etc.)
Hello @joeljfischer. I have updated the PR as requested. Would you please review it? Thank you.

2021-07-28 15:46 UTC, YuriiLokhmatovGitHub commented
Hello @joeljfischer. I have updated the PR as requested. Would you please review it? Thank you.

2021-07-28 15:54 UTC, YuriiLokhmatovGitHub commented
Please note SDLVoiceCommandManagerSpec has nothing to do with this PR and this is the only test that fails.

2021-07-29 17:41 UTC, joeljfischer commented on SmartDeviceLinkTests/RPCSpecs/StructSpecs/SDLTireStatusSpec.m
> +tire6.pressure = @(6.0);
This was not done

2021-07-29 17:41 UTC, joeljfischer commented on SmartDeviceLinkTests/RPCSpecs/StructSpecs/SDLTireStatusSpec.m
> +// make all tires different to prevent misplacement (eg left front != right front etc.)
This was not done

2021-07-29 17:42 UTC, joeljfischer requested changes
See the comments from the unit tests that were not done.

2021-07-29 18:05 UTC, YuriiLokhmatovGitHub commented on SmartDeviceLinkTests/RPCSpecs/StructSpecs/SDLTireStatusSpec.m
> +tire6.pressure = @(6.0);
_Only assign an initial value._ -- If I got it right the 1.0, 2.0, 3.0, 4.0, 5.0, 6.0 are not initial values and must be assigned in a beforeEach block, right?

2021-07-29 18:12 UTC, joeljfischer commented on SmartDeviceLinkTests/RPCSpecs/StructSpecs/SDLTireStatusSpec.m
> +tire6.pressure = @(6.0);
Yes, that’s correct

2021-07-29 19:18 UTC, YuriiLokhmatovGitHub commented
Hello @joeljfischer. I fixed the unit test. Could you please review it? Thank you.

2021-08-03 17:51 UTC, joeljfischer approved these changes

2021-08-03 17:51 UTC, merged