SDL-0255 Enhance BodyInformation vehicle data
smartdevicelink/sdl_ios pull request #1868
Opened 2020-12-06 00:08 UTC by yoooriii

…e data, implement tests for new structs and enum

[Things to note: Pull Requests **must** fix an issue. Discussion about the feature / bug takes place in the issue, discussion of the implementation takes place in the PR. Please also see the [Contributing Guide](https://github.com/smartdevicelink/sdl_ios/blob/master/.github/CONTRIBUTING.md) for information on branch naming and the CLA, and the [SmartDeviceLink GitHub Best Practices](https://d83tozu1c8tt6.cloudfront.net/media/resources/SDL_GitHub_BestPractices.pdf) document for more information on how to enter a pull request. Please create the PR as a draft until it is ready for review. Once this PR is ready for review, please request one from @smartdevicelink/ios and mark the PR as ready for review. 

Also, remember that all new public file headers should be added as public in the `File Inspector / Target Membership` pane, placed in the `SmartDeviceLink/public` folder on the file system, and added to `SmartDeviceLink.h`. Private files should be placed in the `SmartDeviceLink/private` folder.

Delete the above section when you've read it.]

Fixes #[issue number]

### Risk
This PR makes **[no / minor / major]** API changes.

### Testing Plan
- [ ] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [ ] I have run the unit tests with this PR
- [ ] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).

#### Unit Tests
[Describe the unit tests and behaviors added in this PR]

#### Core Tests
[List of tests performed against Core and behaviors verified]

Core version / branch / commit hash / module tested against: [INSERT]
HMI name / version / branch / commit hash / module tested against: [INSERT]

### Summary
[Summary of PR changes]

### Changelog
##### Breaking Changes
* [Breaking change info]

##### Enhancements
* [Enhancement info]

##### Bug Fixes
* [Bug Fix Info]

### Tasks Remaining:
- [ ] [Task 1]
- [ ] [Task 2]

### CLA
- [ ] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

2020-12-06 14:10 UTC, yoooriii commented
Hello @atiwari9. Could you please review the PR? Thank you.

2020-12-07 13:25 UTC, atiwari9 commented
@SatbirTanda  - Please take note..

2020-12-08 09:55 UTC, yoooriii commented
Hello @atiwari9, @mrapitis. Could you please review the PR? Thank you.

2020-12-08 13:59 UTC, atiwari9 commented
@standa1-ford  - Please take note.

2020-12-15 10:44 UTC, standa1-ford commented on SmartDeviceLink-iOS.xcodeproj/project.pbxproj
> +		B3838A3B257C6AB700420C11 /* SDLDoorStatus.h in Headers */ = {isa = PBXBuildFile; fileRef = B3838A39257C6AB600420C11 /* SDLDoorStatus.h */; settings = {ATTRIBUTES = (Public, ); }; };
please add files in proper alphabetical order

2020-12-18 06:32 UTC, standa1-ford approved these changes
Great work!!

2021-01-05 20:01 UTC, NicoleYarroch commented
@yoooriii Can you tag me when you are ready to have Livio review the PR? Thanks!

2021-01-06 12:46 UTC, yoooriii commented
Hello @jordynmackool. Could you review please?

2021-01-06 13:04 UTC, a-prykho commented
Hi @NicoleYarroch , this PR is ready for Livio review.

2021-01-12 17:02 UTC, NicoleYarroch requested changes
I found a few minor things to fix in the code base. Also, the test cases need to be refactored so they work correctly with Xcode's code coverage.

2021-01-12 17:02 UTC, NicoleYarroch commented
@yoooriii Please tag me when you are ready for a re-review. Thanks.

2021-01-14 09:31 UTC, yoooriii commented
> @yoooriii Please tag me when you are ready for a re-review. Thanks.

Hello @NicoleYarroch, I have updated the PR.  Could you please re-review my changes? Thank you.
(for some reason tests on server fail with an error: *'Quick/Quick.h' file not found*. Which is not related to this PR)

2021-01-15 13:17 UTC, NicoleYarroch commented on SmartDeviceLink/public/SDLBodyInformation.m
> +        self.ignitionStatus = ignitionStatus;
Can you change this back to the way the generator created it? Then the formatting will be consistent with most of the other classes in the project.

2021-01-15 14:45 UTC, NicoleYarroch requested changes
Can you change the formatting of the `init`s back to the way it was in the first review? I also requested a few minor changes to the tests.

2021-01-15 14:45 UTC, NicoleYarroch commented on SmartDeviceLinkTests/RPCSpecs/StructSpecs/SDLBodyInformationSpec.m
> +        testStruct = nil;
This `afterEach(^{})` is unnecessary and can be removed.

2021-01-15 14:45 UTC, NicoleYarroch commented on SmartDeviceLinkTests/RPCSpecs/StructSpecs/SDLBodyInformationSpec.m
> +__block SDLBodyInformation* testStruct = nil;
```suggestion
__block SDLBodyInformation *testStruct = nil;
```

2021-01-15 14:45 UTC, NicoleYarroch commented on SmartDeviceLinkTests/RPCSpecs/StructSpecs/SDLBodyInformationSpec.m
> +            NSDictionary* dict = @{
```suggestion
            NSDictionary *dict = @{
```

2021-01-15 14:45 UTC, NicoleYarroch commented on SmartDeviceLinkTests/RPCSpecs/StructSpecs/SDLDoorStatusSpec.m
> +__block SDLDoorStatus* testStruct = nil;
```suggestion
__block SDLDoorStatus *testStruct = nil;
```

2021-01-15 14:45 UTC, NicoleYarroch commented on SmartDeviceLinkTests/RPCSpecs/StructSpecs/SDLDoorStatusSpec.m
> +    });
This `afterEach(^{})` is necessary and can be removed.

2021-01-15 14:45 UTC, NicoleYarroch commented on SmartDeviceLinkTests/RPCSpecs/StructSpecs/SDLDoorStatusSpec.m
> +        testStruct.status = status;
```
testStruct.location = location;
testStruct.status = status;
```
Needs to be inside an `it(@"", ^{})`

2021-01-15 14:45 UTC, NicoleYarroch commented on SmartDeviceLinkTests/RPCSpecs/StructSpecs/SDLDoorStatusSpec.m
> +            NSDictionary* dict = @{
```suggestion
            NSDictionary *dict = @{
```

2021-01-15 14:45 UTC, NicoleYarroch commented on SmartDeviceLinkTests/RPCSpecs/StructSpecs/SDLGateStatusSpec.m
> +//  SDLGateStatus.m
```suggestion
//  SDLGateStatusSpec.m
```

2021-01-15 14:45 UTC, NicoleYarroch commented on SmartDeviceLinkTests/RPCSpecs/StructSpecs/SDLGateStatusSpec.m
> +    });
This `afterEach(^{})` is necessary and can be removed.

2021-01-15 14:45 UTC, NicoleYarroch commented on SmartDeviceLinkTests/RPCSpecs/StructSpecs/SDLGateStatusSpec.m
> +            NSDictionary* dict = @{
```suggestion
            NSDictionary *dict = @{
```

2021-01-15 14:45 UTC, NicoleYarroch commented on SmartDeviceLinkTests/RPCSpecs/StructSpecs/SDLRoofStatusSpec.m
> +__block SDLRoofStatus* testStruct = nil;
```suggestion
__block SDLRoofStatus *testStruct = nil;
```

2021-01-15 14:45 UTC, NicoleYarroch commented on SmartDeviceLinkTests/RPCSpecs/StructSpecs/SDLRoofStatusSpec.m
> +    });
This `afterEach(^{})` is unnecessary and can be removed.

2021-01-15 14:45 UTC, NicoleYarroch commented on SmartDeviceLinkTests/RPCSpecs/StructSpecs/SDLRoofStatusSpec.m
> +            NSDictionary* dict = @{
```suggestion
            NSDictionary *dict = @{
```

2021-01-15 14:46 UTC, NicoleYarroch commented
@yoooriii Can you tag me when you are ready to have Livio review the PR again? Thanks you.

2021-01-21 11:16 UTC, yoooriii commented
Hello @NicoleYarroch. I have updated the PR, could you please proceed ?

2021-01-22 13:52 UTC, NicoleYarroch approved these changes

2021-01-22 13:53 UTC, merged