[SDL-0293] Enable OEM exclusive apps support
smartdevicelink/sdl_ios pull request #1890
Opened 2021-01-12 23:14 UTC by yoooriii

[Things to note: Pull Requests **must** fix an issue. Discussion about the feature / bug takes place in the issue, discussion of the implementation takes place in the PR. Please also see the [Contributing Guide](https://github.com/smartdevicelink/sdl_ios/blob/master/.github/CONTRIBUTING.md) for information on branch naming and the CLA, and the [SmartDeviceLink GitHub Best Practices](https://d83tozu1c8tt6.cloudfront.net/media/resources/SDL_GitHub_BestPractices.pdf) document for more information on how to enter a pull request. Please create the PR as a draft until it is ready for review. Once this PR is ready for review, please request one from @smartdevicelink/ios and mark the PR as ready for review. 

Also, remember that all new public file headers should be added as public in the `File Inspector / Target Membership` pane, placed in the `SmartDeviceLink/public` folder on the file system, and added to `SmartDeviceLink.h`. Private files should be placed in the `SmartDeviceLink/private` folder.

Delete the above section when you've read it.]

Fixes #[issue number]

### Risk
This PR makes **[no / minor / major]** API changes.

### Testing Plan
- [ ] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [ ] I have run the unit tests with this PR
- [ ] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).

#### Unit Tests
[Describe the unit tests and behaviors added in this PR]

#### Core Tests
[List of tests performed against Core and behaviors verified]

Core version / branch / commit hash / module tested against: [INSERT]
HMI name / version / branch / commit hash / module tested against: [INSERT]

### Summary
[Summary of PR changes]

### Changelog
##### Breaking Changes
* [Breaking change info]

##### Enhancements
* [Enhancement info]

##### Bug Fixes
* [Bug Fix Info]

### Tasks Remaining:
- [ ] [Task 1]
- [ ] [Task 2]

### CLA
- [ ] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

2021-01-14 10:31 UTC, yoooriii commented
@SatbirTanda @standa1-ford

2021-01-19 08:55 UTC, standa1-ford commented on Example Apps/Example ObjC/ProxyManager.m
> +    // return [type.make isEqualToString:@"Ford"];
is this a TODO?

2021-01-19 09:22 UTC, standa1-ford commented on SmartDeviceLink/private/SDLControlFramePayloadConstants.m
> +char *const SDLControlFrameVehicleModelYear = "model year";
```suggestion
char *const SDLControlFrameVehicleModelYear = "modelYear";
```

2021-01-19 10:05 UTC, standa1-ford commented on SmartDeviceLink/private/SDLControlFramePayloadRPCStartServiceAck.m
> +BOOL sdl_putStringValue(BsonObject *const payloadObject, const char *key, NSString *value);
this looks like a private function definition; if its a must they should be inside the interface declaration

2021-01-19 10:16 UTC, standa1-ford commented on SmartDeviceLink/private/SDLControlFramePayloadRPCStartServiceAck.m
> +    if (0 < make.length) {
```suggestion
    if (make.length > 0) {
```

2021-01-19 10:25 UTC, standa1-ford commented on SmartDeviceLink/private/SDLLifecycleManager.m
> +        const BOOL shouldProceed = (nil == raiResponse) || [weakSelf shouldProceedWithVehicleType:raiResponse.vehicleType];
```suggestion
        const BOOL shouldProceed = (raiResponse == nil) || [weakSelf shouldProceedWithVehicleType:raiResponse.vehicleType];
```

2021-01-19 10:28 UTC, standa1-ford commented on SmartDeviceLinkTests/ProtocolSpecs/MessageSpecs/SDLControlFramePayloadConstantsSpec.m
> +        expect(SDLControlFrameVehicleModelYear).to(equal("model year"));
After other fix:
```suggestion
        expect(SDLControlFrameVehicleModelYear).to(equal("modelYear"));
```

2021-01-19 10:31 UTC, standa1-ford commented on SmartDeviceLink/private/SDLControlFramePayloadConstants.h
> +// Vehicle type related keys
```suggestion
```

2021-01-19 10:31 UTC, standa1-ford commented on SmartDeviceLink/private/SDLControlFramePayloadRPCStartServiceAck.m
> +        const NSUInteger leng = 1 + [value lengthOfBytesUsingEncoding:NSUTF8StringEncoding];
```suggestion
        const NSUInteger leng = [value lengthOfBytesUsingEncoding:NSUTF8StringEncoding] + 1;
```

2021-01-19 10:32 UTC, standa1-ford commented on SmartDeviceLink/private/SDLLifecycleManager.m
> +        // no need to check it twice (it has already been enabled previously)
```suggestion
```

2021-01-19 10:32 UTC, standa1-ford commented on SmartDeviceLink/private/SDLLifecycleManager.m
> +    // if the delegate present (not nil) and responds to the optional selector then ask it or answer YES instead.
```suggestion
```

2021-01-19 10:35 UTC, standa1-ford approved these changes

2021-01-19 14:10 UTC, joeljfischer commented
@standa1-ford, you can't review and give a bunch of feedback and simultaneously approve a PR. I'm considering this PR as _not_ approved by Ford given that you placed feedback.

2021-01-21 10:36 UTC, yoooriii commented
Hello @standa1-ford. I updated the PR as it was requested. Could you please re-review it? Thank you.

2021-01-22 05:18 UTC, standa1-ford approved these changes
Approved. cc: @joeljfischer
Thanks, will keep that in mind!

2021-01-22 15:54 UTC, jordynmackool commented
@yoooriii / @standa1-ford 

 Can you please resolve the merge conflicts on this PR prior to us reviewing?

2021-01-23 00:07 UTC, yoooriii commented
Hello @jordynmackool. I have merged the develop branch into this one and resolved 2 conflicts in the xcode project file. Could you please proceed? Thank you.

2021-01-28 21:19 UTC, jordynmackool commented
@yoooriii  the proposal markdown file has been updated per the revisions included in the accepted with revisions review issue: [SDL 0293 Revisions - Enable OEM exclusive apps support](https://github.com/smartdevicelink/sdl_evolution/issues/1108). 

Please make the needed updates to this PR and then tag @FrankElias77 to review when ready. Thanks!

2021-02-01 15:08 UTC, yoooriii commented
Hello @FrankElias77. I have updated the PR as it was requested. Could you please review it?
Also please advice if I need to add more tests to increase the code coverage.
Thank you.

2021-02-05 18:43 UTC, FrankElias77 commented on Example Apps/Example ObjC/ProxyManager.m
> +
Why was this function added in this file?

2021-02-08 19:14 UTC, FrankElias77 requested changes
@yoooriii 
- Warning in Objective-c/Swift example apps
- Missing changes in SDLRegisterAppInterfaceResponse that are mentioned in proposal(section: "Addition of "RegisterAppInterface")
- Warnings in the spec files

2021-02-08 20:33 UTC, FrankElias77 commented
@yoooriii Please tag me once these changes are made. Thanks!

2021-02-10 15:36 UTC, joeljfischer commented
@yoooriii, the Java Suite team has written [a new PR](https://github.com/smartdevicelink/sdl_java_suite/pull/1618) for this proposal. Please update this PR or open a new one to match.

2021-02-12 13:53 UTC, yoooriii commented
Hello @FrankElias77. I have updated the PR, could you proceed please? Tnx.
Please note, since a few properties were declared as deprecated I had to update a few extra files and tests to avoid warnings.

2021-02-16 22:43 UTC, FrankElias77 requested changes
@yoooriii Tag me please, once these changes are done

- Increase SDLGlobals's MaxProtocolVersion to 5.4.0
- Warnings on runtime related to Umbrella header. You can fix that by Changing target membership for "SDLTransportType.h" from public to project

2021-02-16 22:43 UTC, FrankElias77 commented on SmartDeviceLink/public/SDLSystemInfo.m
> +
Implement description for this class please
```suggestion

- (NSString *)description
{
    return [NSString stringWithFormat:@"<#format string#>", <#arguments#>];
}

```

2021-02-17 03:29 UTC, FrankElias77 commented on SmartDeviceLink/private/SDLProtocol.m
> +                version = startServiceACKPayload.protocolVersion == nil ? nil : [SDLVersion versionWithString:startServiceACKPayload.protocolVersion];
```suggestion
                version = startServiceACKPayload.protocolVersion == nil ? [SDLVersion versionWithMajor:startServiceACK.header.version minor:0 patch:0] : [SDLVersion versionWithString:startServiceACKPayload.protocolVersion];
```

2021-02-17 03:29 UTC, FrankElias77 commented on SmartDeviceLink/private/SDLProtocol.m
> +                [SDLGlobals sharedGlobals].maxHeadUnitProtocolVersion = (version != nil) ? version : [SDLVersion versionWithMajor:startServiceACK.header.version minor:0 patch:0];
```suggestion
                [SDLGlobals sharedGlobals].maxHeadUnitProtocolVersion = version;
```

2021-02-17 10:32 UTC, yoooriii commented
Hello @FrankElias77. I have updated the PR. Could you please review? Thank you.

2021-02-17 18:10 UTC, FrankElias77 requested changes
@yoooriii Added one more small change. Please tag me once the changes are done!

2021-02-17 21:38 UTC, yoooriii commented
Hello @FrankElias77. I have fixed the PR. Could you please proceed? Thank you.

2021-02-18 22:25 UTC, FrankElias77 approved these changes

2021-02-24 19:17 UTC, joeljfischer commented
Closing in favor of #1919. This pull request had a good amount of unnecessary changes, contained a number of bugs and style issues, and was missing a good chunk of unit tests. Due to the sdl_ios project coming to a development cycle end very soon it was determined that the project maintainer could no longer continue back and forth reviews on this PR. The PM has created a new PR that includes a simpler solution and additional unit tests. Thank you for your understanding.

2021-02-24 19:17 UTC, closed without merging