Fix attempt
smartdevicelink/sdl_ios pull request #1926
Opened 2021-02-26 21:31 UTC by FrankElias77

Fixes #1925 

### Risk
This PR makes **no** API changes.

### Testing Plan
- [ ] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [ ] I have run the unit tests with this PR
- [ ] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).

#### Unit Tests
[Describe the unit tests and behaviors added in this PR]

#### Core Tests
[List of tests performed against Core and behaviors verified]

Core version / branch / commit hash / module tested against: [INSERT]
HMI name / version / branch / commit hash / module tested against: [INSERT]

### Summary
[Summary of PR changes]

### Changelog
##### Breaking Changes
* [Breaking change info]

##### Enhancements
* [Enhancement info]

##### Bug Fixes
* [Bug Fix Info]

### Tasks Remaining:
- [ ] [Task 1]
- [ ] [Task 2]

### CLA
- [ ] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

2021-03-02 16:08 UTC, joeljfischer requested changes

2021-03-02 16:08 UTC, joeljfischer commented on .github/workflows/test.yml
> +        runs-on: ubuntu-18.04
```suggestion
        runs-on: ubuntu-20.04
```

Will this work on the latest LTS?

2021-03-03 19:25 UTC, FrankElias77 commented on .github/workflows/test.yml
> +        runs-on: ubuntu-18.04
It does, without displaying any warning

2021-03-03 19:54 UTC, joeljfischer approved these changes

2021-03-03 19:54 UTC, merged