Fixed random failures in SDLVoiceCommandManagerSpec due to operations being canceled
smartdevicelink/sdl_ios pull request #2002
Opened 2021-05-26 14:54 UTC by FrankElias77

Fixes #2001 

### Risk
This PR makes **no** API changes.

### Testing Plan
- [x] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [x] I have run the unit tests with this PR
- [ ] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).

#### Unit Tests
N/A

#### Core Tests
N/A

Core version / branch / commit hash / module tested against: N/A
HMI name / version / branch / commit hash / module tested against: N/A

### Summary
Canceled the current executing operation when a new operation is added

### Changelog
##### Breaking Changes
* N/A

##### Enhancements
* N/A

##### Bug Fixes
* Canceled the current executing operation when a new operation is added

### Tasks Remaining:
N/A

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

2021-05-26 15:41 UTC, joeljfischer requested changes

2021-05-26 15:41 UTC, joeljfischer commented on SmartDeviceLink/private/SDLVoiceCommandManager.m
> +    }
This seems incorrect. You have changed cancelling all operations to only change the executing one. So if you have operations:

```
Op1 - executing
Op2 - waiting
```

And add Op3, this code used to:

```
Op1 - canceled
Op2 - canceled
Op3 - waiting
```

The next op to execute would be op 3, correctly. With your change:

```
Op1 - cancelled
Op2 - waiting
Op3- waiting
```

As you can see, this is incorrect.

2021-06-22 18:33 UTC, joeljfischer requested changes

2021-06-22 18:33 UTC, joeljfischer commented on SmartDeviceLinkTests/DevAPISpecs/SDLVoiceCommandManagerSpec.m
> +                expect(testManager.transactionQueue.operations.firstObject.isExecuting).to(equal(false));
```suggestion
                expect(testManager.transactionQueue.operations.firstObject.isExecuting).to(beFalse());
```

2021-06-22 18:33 UTC, joeljfischer commented on SmartDeviceLinkTests/DevAPISpecs/SDLVoiceCommandManagerSpec.m
> +            // when new voice commands is identical to the existing ones
```suggestion
            // when new voice commands are identical to the existing ones
```

2021-06-22 18:33 UTC, joeljfischer commented on SmartDeviceLinkTests/DevAPISpecs/SDLVoiceCommandManagerSpec.m
> +            // when new voice commands are set
```suggestion
            // when new voice commands are different from the existing ones
```

2021-06-22 18:33 UTC, joeljfischer commented on SmartDeviceLinkTests/DevAPISpecs/SDLVoiceCommandManagerSpec.m
> +                    // should update the second operation
```suggestion
```

2021-06-22 18:33 UTC, joeljfischer commented on SmartDeviceLinkTests/DevAPISpecs/SDLVoiceCommandManagerSpec.m
> +                // should queue another operation
```suggestion
```

This isn't necessary because it's a single it in the group

2021-06-22 18:33 UTC, joeljfischer commented on SmartDeviceLinkTests/DevAPISpecs/SDLVoiceCommandManagerSpec.m
>      // updating voice commands
```suggestion
    // when the hmi is ready
```

2021-06-23 17:29 UTC, FrankElias77 commented on SmartDeviceLinkTests/DevAPISpecs/SDLVoiceCommandManagerSpec.m
>          it(@"should properly update a command", ^{
Can you please be more specific, do you mean the description for `it`?

2021-06-23 17:36 UTC, joeljfischer commented on SmartDeviceLinkTests/DevAPISpecs/SDLVoiceCommandManagerSpec.m
>          it(@"should properly update a command", ^{
I meant the name of the describe I believe?

2021-06-23 19:34 UTC, joeljfischer approved these changes

2021-06-23 19:35 UTC, merged