Update choice set manager to handle pending presentations better
smartdevicelink/sdl_ios pull request #2019
Opened 2021-07-06 20:05 UTC by joeljfischer

Fixes #2018 

### Risk
This PR makes **no** API changes.

### Testing Plan
- [x] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [ ] I have run the unit tests with this PR
- [x] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).

#### Unit Tests
TODO

#### Core Tests
* Tested sending a presentation, then sending another presentation when the first has a button pressed.

Core version / branch / commit hash / module tested against: Manticore (SDL v7.1.1)
HMI name / version / branch / commit hash / module tested against: Manticore (Generic HMI v0.10.0)

### Summary
[Summary of PR changes]

### Changelog
##### Breaking Changes
* [Breaking change info]

##### Enhancements
* [Enhancement info]

##### Bug Fixes
* [Bug Fix Info]

### Tasks Remaining:
- [ ] [Task 1]
- [ ] [Task 2]

### CLA
- [ ] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

2021-08-05 20:49 UTC, FrankElias77 reviewed
1. Preload choice cells
2. Present choice cells
3. Select any cell
After step num 3, selected cells do not trigger `didSelectChoice` delegate method of `SDLChoiceSetDelegate`

In addition, I was unable to find the voice commands associated with the choice cells after presenting choice set

2021-08-09 15:21 UTC, joeljfischer commented
@FrankElias77 The first issue is fixed. The second is definitely being sent, but it may not function on certain head units?

2021-08-24 19:27 UTC, FrankElias77 submitted a review, later dismissed

2021-09-03 13:20 UTC, joeljfischer commented on SmartDeviceLink/private/SDLChoiceSetManager.m
> +    if ([self.currentState isEqualToString:SDLChoiceManagerStateShutdown]) {
Change to `!Ready` instead

2021-09-03 13:26 UTC, joeljfischer commented on SmartDeviceLink/private/SDLPreloadPresentChoicesOperation.m
> +    }
Move before L173

2021-09-08 19:10 UTC, FrankElias77 approved these changes

2021-09-14 16:24 UTC, FrankElias77 submitted a review, later dismissed

2021-09-14 21:42 UTC, FrankElias77 requested changes

2021-09-14 21:42 UTC, FrankElias77 commented on SmartDeviceLink/private/SDLPreloadPresentChoicesOperation.m
> +/// @param cells The menu cells to get artwork from
Please add missing descriptions for the remaining params

2021-09-15 18:35 UTC, FrankElias77 submitted a review, later dismissed

2021-09-17 18:50 UTC, merged