Security queries are not implemented to spec
smartdevicelink/sdl_ios pull request #2026
Opened 2021-07-28 14:02 UTC by FrankElias77

Fixes #2024 

### Risk
This PR makes **[no / minor / major]** API changes.

### Testing Plan
- [ ] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [ ] I have run the unit tests with this PR
- [ ] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).

#### Unit Tests
[Describe the unit tests and behaviors added in this PR]

#### Core Tests
[List of tests performed against Core and behaviors verified]

Core version / branch / commit hash / module tested against: [INSERT]
HMI name / version / branch / commit hash / module tested against: [INSERT]

### Summary
[Summary of PR changes]

### Changelog
##### Breaking Changes
* [Breaking change info]

##### Enhancements
* [Enhancement info]

##### Bug Fixes
* [Bug Fix Info]

### Tasks Remaining:
- [ ] [Task 1]
- [ ] [Task 2]

### CLA
- [ ] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

2021-08-20 15:11 UTC, joeljfischer requested changes

2021-08-20 15:11 UTC, joeljfischer commented on SmartDeviceLinkTests/RPCSpecs/PayloadSpecs/SDLSecurityQueryPayloadSpec.m
> +    it (@"Should convert from byte data correctly", ^ {
```suggestion
    it(@"should convert from byte data correctly", ^{
```

Fix all misformatting like this

2021-08-20 15:11 UTC, joeljfischer commented on SmartDeviceLinkTests/RPCSpecs/PayloadSpecs/SDLSecurityQueryPayloadSpec.m
> +    NSData* binaryData = [NSData dataWithBytes:"PrimitiveString" length:strlen("PrimitiveString")];
We don't want to test an RPC like this. We want to test something like what we'd really see with JSON string and error code and binary data like we'll see.

2021-08-30 17:23 UTC, joeljfischer requested changes

2021-09-01 14:16 UTC, joeljfischer requested changes

2021-09-01 14:25 UTC, joeljfischer approved these changes

2021-09-07 13:36 UTC, joeljfischer requested changes

2021-09-08 14:22 UTC, joeljfischer requested changes

2021-09-08 14:22 UTC, joeljfischer commented on SmartDeviceLink/public/SDLSecurityQueryErrorCode.h
> +//
This new file was placed in the "public" folder, but it's a project file and non-public, so this project no longer works in Cocoapods. Please move this class' files to the "private" folder and fix the project.

2021-09-08 17:04 UTC, joeljfischer approved these changes

2021-09-14 12:34 UTC, yoooriii reviewed
Would you please implement unit tests in SDLProtocolSpec since the protocol has changed and the updated code is not covered with tests. Also could you please review Codecov messages for it? Thank you.

2021-09-14 12:34 UTC, yoooriii commented on SmartDeviceLinkTests/RPCSpecs/PayloadSpecs/SDLSecurityQueryPayloadSpec.m
> +    it(@"should set and get correctly", ^ {
Please remove whitespaces in blocks:  `^ {` ==> `^{`
There are a few more such cases I do not highlight each one.

2021-09-14 12:34 UTC, yoooriii commented on SmartDeviceLinkTests/RPCSpecs/PayloadSpecs/SDLSecurityQueryPayloadSpec.m
> +#import "SDLSecurityQueryErrorCode.h"
Please reorder files alphabetically.

2021-09-14 12:34 UTC, yoooriii commented on SmartDeviceLinkTests/RPCSpecs/PayloadSpecs/SDLSecurityQueryPayloadSpec.m
> +        expect([NSString stringWithUTF8String:[testPayload binaryData].bytes]).to(equal(@"PrimitiveString"));
Be careful when converting bytes to strings and back again. Generally you should avoid using bytes directly. 
```
NSString *stringData = [[NSString alloc] initWithData:[testPayload binaryData] encoding:NSUTF8StringEncoding];
```
Also I propose to replace string literal to a const like following:
```
static NSString *const primitiveString = @"PrimitiveString";
```
You can use this string in all other places.

2021-09-14 12:34 UTC, yoooriii commented on SmartDeviceLinkTests/RPCSpecs/PayloadSpecs/SDLSecurityQueryPayloadSpec.m
> +__block SDLSecurityQueryPayload* testPayload;
```
__block SDLSecurityQueryPayload *testPayload = nil;
```
Please nullify the pointer.

2021-09-14 12:34 UTC, yoooriii commented on SmartDeviceLinkTests/RPCSpecs/PayloadSpecs/SDLSecurityQueryPayloadSpec.m
> +__block NSDictionary* dict = @{@"id": @"3", @"text": @"SDL does not support encryption"};
Please do not use `__block` here, it is confusing. The `dict` is not going to change in this test suite. Also could you please dub it somehow differently, for instance `testDictionary`

2021-09-14 12:34 UTC, yoooriii commented on SmartDeviceLinkTests/RPCSpecs/PayloadSpecs/SDLSecurityQueryPayloadSpec.m
> +    NSMutableData *data = [NSMutableData dataWithCapacity:12 + jsonData.length];
If you want to allocate data buffer beforehand then you had better do it a bit differently:
```
NSMutableData *data = [NSMutableData dataWithCapacity:sizeof(header) + jsonData.length + binaryData.length];
```

2021-09-14 12:34 UTC, yoooriii commented on SmartDeviceLinkTests/RPCSpecs/PayloadSpecs/SDLSecurityQueryPayloadSpec.m
> +    NSData* binaryData = [NSData dataWithBytes:"PrimitiveString" length:strlen("PrimitiveString")];
Be careful with string encoding especially avoid using raw bytes and repeating string literals, I would propose to make it other way round:
```
NSData *binaryData = [primitiveString dataUsingEncoding:NSUTF8StringEncoding];
```
And you can define `primitiveString` once and use it everywhere.

2021-09-14 12:34 UTC, yoooriii commented on SmartDeviceLinkTests/RPCSpecs/PayloadSpecs/SDLSecurityQueryPayloadSpec.m
> +    [data appendBytes:&header length:12];
Please avoid using magic numbers, we can do it a bit differently:
```
[data appendBytes:&header length:sizeof(header)];
```

2021-09-14 12:34 UTC, yoooriii commented on SmartDeviceLinkTests/RPCSpecs/PayloadSpecs/SDLSecurityQueryPayloadSpec.m
> +        expect([NSString stringWithUTF8String:[constructedPayload binaryData].bytes]).to(equal(@"PrimitiveString"));
I would propose to use other string function:
```
NSString *stringData = [[NSString alloc] initWithData:[testPayload binaryData] encoding:NSUTF8StringEncoding];
expect(stringData).to(equal(primitiveString));
```

2021-09-14 12:34 UTC, yoooriii commented on SmartDeviceLinkTests/RPCSpecs/PayloadSpecs/SDLSecurityQueryPayloadSpec.m
> +QuickSpecEnd
Please implement one more test for the following method:
```
- (instancetype)initWithQueryType:(SDLSecurityQueryType)queryType queryID:(SDLSecurityQueryId)queryID sequenceNumber:(UInt32)sequenceNumber jsonData:(nullable NSData *)jsonData binaryData:(nullable NSData *)binaryData;
```

2021-09-14 12:34 UTC, yoooriii commented on SmartDeviceLinkTests/RPCSpecs/PayloadSpecs/SDLSecurityQueryPayloadSpec.m
> +    testPayload.binaryData = [NSData dataWithBytes:"PrimitiveString" length:strlen("PrimitiveString")];
Please use string data `primitiveString` defined in one place without repeating itself:
```
testPayload.binaryData = [primitiveString dataUsingEncoding:NSUTF8StringEncoding];
```

2021-09-14 12:41 UTC, joeljfischer commented
Hello @yoooriii, this is not the kind of review that we are looking for from the steering committee. Please place your review comments on the steering committee discussion (https://github.com/smartdevicelink/sdl_ios/discussions/2030) and limit your comments to whether the changes in the PR continue to support your head units' security capabilities. Thank you.

2021-09-22 13:29 UTC, merged