Bugfix/issue 2105 Fix screenParams nil and mediaClockFormats empty
smartdevicelink/sdl_ios pull request #2106
Opened 2022-08-17 20:33 UTC by jshivabeharry

Fixes #2105 

### Risk
This PR makes no API changes.

### Testing Plan
- [x] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [x] I have run the unit tests with this PR
- [x] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).

#### Unit Tests
Added unit test in `SDLSystemCapabilityManagerSpec` to verify when updated `displayCapabilities` properties `screenParams` and `mediaClockFormats` stays the same

#### Core Tests
Accessed `screenParams` and `mediaClockFormats` from `systemCapabilityManager`

Core version / branch / commit hash / module tested against: sdl_core 8.1.0 (manticore)
HMI name / version / branch / commit hash / module tested against: generic_hmi 0.12.0 (manticore)

### Summary
- `sdl_updateDeprecatedDisplayCapabilities` sets the mediaClockFormats and screenParams to the initialized values.
- One unit test added in `SDLSystemCapabilityManagerSpec` for verifying `displayCapabilities` after update.

### Changelog
##### Breaking Changes
* NA

##### Enhancements
* NA

##### Bug Fixes
* screenParams and mediaClockFormats are not nil or empty

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

2022-08-18 16:00 UTC, jshivabeharry commented
Updated  pull request and pushed change to reflect windowID is `nil` issue

2022-08-19 15:42 UTC, joeljfischer requested changes

2022-08-19 15:42 UTC, joeljfischer commented on SmartDeviceLink/public/SDLSystemCapabilityManager.m
> +        windowCapability.windowID = [NSNumber<SDLUInt> numberWithUnsignedLong:windowID];
```suggestion
        // A nil windowID is assumed to be the DefaultWindow according to the spec, but that can be hard for developers to check, so set it explicitly.
        windowCapability.windowID = [NSNumber numberWithUnsignedLong:currentWindowID];
```

I think this is a little clearer

2022-08-19 15:42 UTC, joeljfischer commented on SmartDeviceLink/public/SDLSystemCapabilityManager.m
> +    convertedCapabilities.mediaClockFormats = self.displayCapabilities.mediaClockFormats ? self.displayCapabilities.mediaClockFormats : @[];
```suggestion
    convertedCapabilities.mediaClockFormats = self.displayCapabilities.mediaClockFormats ?: @[];
```

I didn't check, but I believe this is equivalent.

2022-08-19 15:42 UTC, joeljfischer commented on SmartDeviceLinkTests/SDLSystemCapabilityManagerSpec.m
> +            it(@"should retrieve window id if window id is missing in window capabilities", ^{
```suggestion
            it(@"should set the default window id if window id is missing", ^{
```

2022-08-19 15:42 UTC, joeljfischer commented on SmartDeviceLinkTests/SDLSystemCapabilityManagerSpec.m
> +                // set window id to nil. windowID can be potentialy nil in real applications
```suggestion
                // Set window id to nil. windowID can be potentially nil in real applications
```

2022-08-19 15:42 UTC, joeljfischer commented on SmartDeviceLinkTests/SDLSystemCapabilityManagerSpec.m
> +                expect([testSystemCapabilityManager windowCapabilityWithWindowID:0].windowID).to(equal(0));
```suggestion
                expect(testSystemCapabilityManager.defaultMainWindowCapability.windowID).to(equal(SDLPredefinedWindowsDefaultWindow));
                expect([testSystemCapabilityManager windowCapabilityWithWindowID:0].windowID).to(equal(SDLPredefinedWindowsDefaultWindow));
```

2022-08-19 15:42 UTC, joeljfischer commented on SmartDeviceLinkTests/SDLSystemCapabilityManagerSpec.m
> +        it(@"it should keep maintain screenParams and mediaClockFormats values in display capabilities", ^{
I feel like this should just be a part of the test above it?

2022-08-22 13:08 UTC, joeljfischer requested changes

2022-08-22 13:08 UTC, joeljfischer commented on SmartDeviceLinkTests/SDLSystemCapabilityManagerSpec.m
> +            testSystemCapabilityManager.displayCapabilities = testDisplayCapabilities;
Doesn't look like you have an expect for screen params or media clock formats?

2022-08-22 14:58 UTC, joeljfischer approved these changes

2022-09-13 13:22 UTC, merged